### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by john-doherty** [Larney11/mock-fetch-api#5]
Hello, I really like the simplicity of this library but it does have a few issues, such as:

 * Inability to run unit tests after a git clone due to no test libs in package.json
 * unnecessary function wrapper `(function(global) {`

Are you still maintaining it?

Thanks.

**Comment by Larney11** [comment]
Hi, sorry for the late reply. I am no longer maintaining this repository.

**Comment by john-doherty** [comment]
Hi, yes I figured that so created my own [fetch-reply-with](https://github.com/john-doherty/fetch-reply-with) ;)
